=== bobanum/enigma/public/data/enigma.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Définition des types -->
  <xs:complexType name="Clue">
    <xs:sequence>
      <xs:element name="part" type="Part" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Part" mixed="true">
    <xs:sequence>
      <xs:element name="ref" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="prop" type="xs:string" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="formula" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="Case">
    <xs:sequence>
      <xs:element name="prop" minOccurs="4" maxOccurs="4">
        <xs:complexType>
          <xs:attribute name="prop" type="xs:string" />
          <xs:attribute name="choice" type="xs:string" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="recap" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="Finding">
    <xs:attribute name="clue" type="xs:string" />
    <xs:attribute name="formula" type="xs:string" />
    <xs:attribute name="deducted" type="xs:boolean" default="false" />
  </xs:complexType>
  <xs:complexType name="Prop">
    <xs:sequence>
      <xs:element name="choice" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="id" type="xs:string" use="required" />
              <xs:attribute name="abbr" type="xs:string" />
              <xs:attribute name="attribute" type="xs:string" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="ordered" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="HTML" mixed="true">
    <xs:sequence>
      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
    </xs:sequence>
  </xs:complexType>

  <!-- Définition des éléments -->
  <xs:element name="enigma">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="intro" type="HTML" />
        <xs:element name="pre" type="HTML" minOccurs="0" />
        <xs:element name="post" type="HTML" minOccurs="0" />
        <xs:element name="style" type="xs:string" minOccurs="0" />
        <xs:element name="props">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="prop" type="Prop" maxOccurs="unbounded">
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="clues">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="clue" type="Clue" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="solution" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="case" minOccurs="0" maxOccurs="unbounded" type="Case" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="findings" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="finding" minOccurs="0" maxOccurs="unbounded" type="Finding" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="title" type="xs:string" use="required" />
      <xs:attribute name="reference" type="xs:string" />
      <xs:attribute name="image" type="xs:string" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bobanum/enigma/public/data/pandore.xml
<enigma
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="enigma.xsd"
title="Boîte de Pandore"
reference="Le cube de jeux. #171"
image="img/derek.svg">
	<intro> Pandore Persimmons est l'animateur d'un jeu questionnaire durant lequel les concurrents méritent le droit d'ouvrir une des boites que l'on voit dans l'illustration. Le contenu des boites peut être très intéressant ou... nul. Pandore essaie de convaincre les participants d'abandonner leur chance d'ouvrir une boite en leur offrant de l'argent. Cette fois-ci, ça n'a pas marché. A l'aide des indices ci-dessous, trouvez l'ordre dans lequel les concurrents ouvriront les boites, quelle boite ils ouvriront et ce qu'ils gagneront. </intro>
	<style>
		.avant: {
		position: absolute,
		right: .75in,
		bottom: .75in,
		height: 23pc
		},
		.tableau: {
		font-size: 11pt
		},
		.indices ol: {
		font-size: 11pt,
		columns: 2,
		padding: 0,
		column-rule: 1px dotted black
		},
		.indices li: {
		margin: 0 0 0.5em 0,
		margin-left: 1.5em,
		page-break-inside: avoid
		},
		p.intro: {
		line-height: 1.2,
		margin: 1em 0
		},
		.colonnes: {
		grid-template-columns: auto
		},
		.truc: {
		left: 18pc,
		bottom: 7pc
		}
	</style>
	<props>
		<prop id="boite" name="Boite" ordered="true">
			<choice id="no1" abbr="no1">1</choice>
			<choice id="no2" abbr="no2">2</choice>
			<choice id="no3" abbr="no3">3</choice>
			<choice id="no4" abbr="no4">4</choice>
			<choice id="no5" abbr="no5">5</choice>
			<choice id="no6" abbr="no6">6</choice>
		</prop>
		<prop id="concurrents" name="Concurrents">
			<choice id="jim" abbr="J">Jim</choice>
			<choice id="lynne" abbr="L">Lynne</choice>
			<choice id="michael" abbr="M">Michaël</choice>
			<choice id="robert" abbr="R">Robert</choice>
			<choice id="sharon" abbr="Sh">Sharon</choice>
			<choice id="susanne" abbr="Su">Suzanne</choice>
		</prop>
		<prop id="prix" name="Prix" ordered="true">
			<choice id="savon" abbr="S" attribute="type=objet">Savon</choice>
			<choice id="cuillere" abbr="C" attribute="type=objet">Cuillère</choice>
			<choice id="a50" abbr="50¢" attribute="type=argent">0,50$</choice>
			<choice id="a100" abbr="100" attribute="type=argent">100$</choice>
			<choice id="a1k" abbr="1k" attribute="type=argent">1000$</choice>
			<choice id="a5k" abbr="5k" attribute="type=argent">5000$</choice>
		</prop>
		<prop id="ordre" name="Ordre" ordered="true">
			<choice id="premier" abbr="1er">Premier</choice>
			<choice id="deuxieme" abbr="2e">Deuxième</choice>
			<choice id="troisieme" abbr="3e">Troisième</choice>
			<choice id="quatrieme" abbr="4e">Quatrième</choice>
			<choice id="cinquieme" abbr="5e">Cinquième</choice>
			<choice id="sixieme" abbr="6e">Sixième</choice>
		</prop>
	</props>
	<clues>
		<!-- Operators: 
			= : Equals to
			!= : Different from
			&lt; : Lower than
			&gt; : Higher than
		-->
		<clue>
			<part formula="ordre#≠boite#">L'<ref prop="ordre">ordre des concurrents</ref> ne correspond jamais au <ref prop="numero">numéro de la boite</ref>.</part>
		</clue>
		<clue>
			<part formula="concurrents.lynne=ordre.no2"><ref prop="concurrents.lynne">Lynne</ref>, qui a ouvert la <ref prop="ordre.no2">deuxième boite</ref>,</part>
			<part formula="concurrents.lynne:prix=[type=argent]">a gagné de l'<ref prop="prix">argent</ref>,</part>
			<part formula="concurrents.sharon:prix=[type=argent];concurrents.lynn:prix#&lt;concurrents.sharon:prix#;">mais moins que <ref prop="concurrents.sharon">Sharon</ref></part>
			<part formula="concurrents.lynne:ordre#-concurrents.sharon:ordre#&gt;1;">dont le tour précédait celui de <ref prop="concurrents.lynne">Lynne</ref></part>
			<part>mais n'était pas <ref prop="ordre">immédiatement avant</ref>.</part>
		</clue>
		<clue>
			<part><ref prop="concurrents.michael">Michael</ref>, dont le tour est venu après celui du gagnant de <ref prop="prix.100">100$</ref>,</part>
			<part>a ouvert une boîte à droite de celle du <ref prop="prix.5k">gagnant</ref>, mais pas <ref prop="ordre">juste à côté</ref>.</part>
		</clue>
		<clue>
			<part>La boite contenant un morceau de <ref prop="prix.savon">savon</ref> se trouvait juste à gauche de celle ouverte par le <ref prop="ordre.5">cinquième concurrent</ref>.</part>
			<part>La boite choisie par <ref prop="concurrents.jim">Jim</ref> était à gauche que ces deux boîtes.</part>
		</clue>
		<clue>
			<part>Le tour du concurrent qui a gagné une <ref prop="prix.cuillere">cuillère de bois</ref> était juste avant celui du concurrent qui a gagné <ref prop="prix.50">0,50$</ref>.</part>
			<part>La boite avec la cuillere était juste à droite de celle contenant <ref prop="prix.1000">1000$</ref>.</part>
		</clue>
		<clue>
			<part><ref prop="concurrents.susanne">Susanne</ref> a ouvert la boite juste a droite de celle choisie par <ref prop="concurrents.robert">Robert</ref></part>
			<part>qui a joué juste après elle.</part>
		</clue>
		<clue>
			<part>Les <ref prop="concurrents">hommes</ref> n'ont pas ouvert de boites <ref prop="ordre">adjacentes</ref>.</part>
			<part>Le gagnant de <ref prop="prix.5k">5000$</ref> est la seule personne dont la boite se trouvait à droite de celle d'un <ref prop="concurrents">homme</ref></part>
			<part>et à gauche de celle d'une <ref prop="concurrents">femme</ref>.</part>
		</clue>
	</clues>
</enigma>

=== bobanum/enigma/public/data/perroquet.xml
<enigma
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../enigma.xsd"
    title="Le perroquet"
    reference="Le cube de jeux. #223"
    image="img/perroquet.svg">
    <intro>J'ai acheté un perroquet récemment avec la ferme intention de lui apprendre à parler. Malheureusement, il semble que quelqu'un ait réussi avant moi. J'ai reçu cinq visiteurs à des jours différents la semaine dernière - deux membres de ma famille et trois réparateurs - et le perroquet leur a répondu de façon plutôt impolie lorsqu'ils lui ont adressé la parole. À l'aide des clues ci-dessous, pouvez-vous trouver quel jour chacun des visiteurs est venu, ce qu'il a dit à mon perroquet et ce que celui-ci leur a répondu?</intro>
    <style>
        .intro: {
            line-height: 1.5;
        }
        .avant: {
            position:absolute;
            bottom: 2in;
            right:.5in;
            width:5in;
        }
    </style>
    <props>
        <prop id="jour" name="Jour">
            <choice id="lundi" abbr="Lundi">Lundi</choice>
            <choice id="mardi" abbr="Mardi">Mardi</choice>
            <choice id="mercredi" abbr="Mercredi">Mercredi</choice>
            <choice id="jeudi" abbr="Jeudi">Jeudi</choice>
            <choice id="vendredi" abbr="Vendredi">Vendredi</choice>
        </prop>
        <prop id="reponse" name="Réponse">
            <choice id="disparait" abbr="Disparaît!">Disparaît!</choice>
            <choice id="fouslecamp" abbr="Fous le camp!">Fous le camp!</choice>
            <choice id="ecrase" abbr="Écrase!">Écrase!</choice>
            <choice id="pasmoi" abbr="Pas moi!">Pas moi!</choice>
            <choice id="etpuis" abbr="Et puis?">Et puis?</choice>
        </prop>
        <prop id="salutation" name="Salutation">
            <choice id="bonjour" abbr="Bonjour!">Bonjour!</choice>
            <choice id="allo" abbr="Allo!">Allo!</choice>
            <choice id="cava" abbr="Ça va?">Ça va?</choice>
            <choice id="contentdetevoir" abbr="Content de te voir!">Content de te voir!</choice>
            <choice id="tuesbienjoli" abbr="Tu es bien! joli!">Tu es bien! joli!</choice>
        </prop>
        <prop id="visiteur" name="Visiteur">
            <choice id="tante" abbr="T" attribute="gender=female">Tante</choice>
            <choice id="electricien" abbr="É" attribute="gender=male">Électricien</choice>
            <choice id="plombier" abbr="P" attribute="gender=male">Plombier</choice>
            <choice id="reparateur" abbr="R" attribute="gender=male">Réparateur</choice>
            <choice id="soeur" abbr="S" attribute="gender=female">Soeur</choice>
        </prop>
    </props>
    <clues>
        <clue>
            <part>L'<ref prop="visiteur">homme</ref> qui est venu à la maison le <ref prop="jour.mercredi">mercredi</ref></part>
            <part>a salué le perroquet d'un joyeux <ref prop="salutation.bonjour">Bonjour!</ref>;</part>
            <part>L'<ref prop="visiteur.electricien">électricien</ref> est venu le <ref prop="jour">lendemain</ref>.</part>
        </clue>
        <clue>
            <part><ref prop="reponse.pasmoi">Pas moi!</ref> est la réponse qu'a servie le perroquet lorsqu'on lui a dit: <ref prop="salutation.contentdetevoir">Content de te voir!</ref></part>
        </clue>
        <clue>
            <part>Ce n'est pas au <ref prop="visiteur.reparateur">réparateur de télé</ref> que le perroquet a répondu: <ref prop="reponse.fouslecamp">Fous le camp!</ref></part>
        </clue>
        <clue>
            <part>Le <ref prop="visiteur.plombier">plombier</ref> a salué l'animal en disant: <ref prop="salutation.allo">Allo!</ref>,</part>
            <part>mais <ref prop="visiteur.plombier">il</ref> n'est pas le visiteur du <ref prop="jour.mardi">mardi</ref>.</part>
            <part><ref prop="jour.mardi">Ce dernier</ref> s'est fait répondre: <ref prop="reponse.ecrase">Écrase!</ref></part>
        </clue>
        <clue>
            <part>Ma <ref prop="visiteur.soeur">soeur</ref>, qui n'est pas venue le <ref prop="jour.lundi">lundi</ref>,</part>
            <part>s'est adressée tout gentiment à l'oiseau qui lui a répondu: <ref prop="reponse.etpuis">Et puis?</ref></part>
        </clue>
        <clue>
            <part>Le visiteur du <ref prop="jour.vendredi">vendredi</ref> ne s'est pas adressé à l'animal en disant: <ref prop="salutation.tuesbienjoli">Tu es bien! joli!</ref></part>
        </clue>
    </clues>
    <solution>
        <case recap="Le mercredi, l'Électricien a dit 'Bonjour!' au perroquet et ce dernier a répondu 'Pas moi!'">
            <prop prop="jour" choice="mercredi" />
            <prop prop="visiteur" choice="electricien" />
            <prop prop="salutation" choice="bonjour" />
            <prop prop="reponse" choice="pasmoi" />
        </case>
        <case recap="Le lundi, la Soeur a dit 'Content de te voir!' au perroquet et ce dernier a répondu 'Et puis?'">
            <prop prop="jour" choice="lundi" />
            <prop prop="visiteur" choice="soeur" />
            <prop prop="salutation" choice="contentdetevoir" />
            <prop prop="reponse" choice="etpuis" />
        </case>
        <case recap="Le jeudi, le Réparateur a dit 'Écrase!' au perroquet et ce dernier a répondu 'Allo!'">
            <prop prop="jour" choice="jeudi" />
            <prop prop="visiteur" choice="reparateur" />
            <prop prop="salutation" choice="allo" />
            <prop prop="reponse" choice="ecrase" />
        </case>
        <case recap="Le mardi, le Plombier a dit 'Allo!' au perroquet et ce dernier a répondu 'Écrase!'">
            <prop prop="jour" choice="mardi" />
            <prop prop="visiteur" choice="plombier" />
            <prop prop="salutation" choice="allo" />
            <prop prop="reponse" choice="ecrase" />
        </case>
        <case recap="Le vendredi, la Tante a dit 'Tu es bien! joli!' au perroquet et ce dernier a répondu 'Fous le camp!'">
            <prop prop="jour" choice="vendredi" />
            <prop prop="visiteur" choice="tante" />
            <prop prop="salutation" choice="tuesbienjoli" />
            <prop prop="reponse" choice="fouslecamp" />
        </case>
    </solution>
</enigma>

=== bobanum/enigma/public/derek.xml
<enigma
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="enigma.xsd"
	title="Derek et le détecteur de métal"
	reference="Cube de jeux. #206"
	image="derek.svg">
	<intro>Depuis qu'il a acheté un détecteur de métal, Derek a saisi chaque occasion pour essayer de trouver un trésor. La semaine dernière, il s'est servi de son jouet à cinq reprises, mais chaque fois il mettait tant de temps à trouver quelque chose qu'il abandonnait au premier objet trouvé. À l'aide des indices à droite, pouvez-vous classer les excursions de Derek dans le bon ordre en identifiant les lieux où il a cherché, le temps qu'il a passé à chercher et ce qu'il a éventuellement trouvé?</intro>
	<style>
		.tableau {
		font-size:13pt;
		}
		.indices ol {
		font-size:1em;
		},
		img.extra {
		position: absolute;
		right: .25in;
		bottom: .75in;
		height: 100mm;
		}
	</style>
	<props>
		<prop id="sortie" name="Sortie">
			<choice id="premiere" abbr="1re">Première</choice>
			<choice id="deuxieme" abbr="2e">Deuxième</choice>
			<choice id="troisieme" abbr="3e">Troisième</choice>
			<choice id="quatrieme" abbr="4e">Quatrième</choice>
			<choice id="cinquieme" abbr="5e">Cinquième</choice>
		</prop>
		<prop id="objet" name="Objet">
			<choice id="capsule" abbr="Cap">Capsule</choice>
			<choice id="poignee" abbr="P">Poignée</choice>
			<choice id="cle" abbr="CA">Clé anglaise</choice>
			<choice id="cuillere" abbr="Cui">Cuillère</choice>
			<choice id="jouet" abbr="Jou">Jouet</choice>
		</prop>
		<prop id="duree" name="Durée">
			<choice id="15" abbr="15">15 minutes</choice>
			<choice id="20" abbr="20">20 minutes</choice>
			<choice id="25" abbr="25">25 minutes</choice>
			<choice id="35" abbr="35">35 minutes</choice>
			<choice id="40" abbr="40">40 minutes</choice>
		</prop>
		<prop id="lieu" name="Lieu">
			<choice id="plage" abbr="Pl">Plage</choice>
			<choice id="champ" abbr="Ch">Champ</choice>
			<choice id="jardinami" abbr="JA">Jardin d'un ami</choice>
			<choice id="sonjardin" abbr="JdD">Jardin de Derek</choice>
			<choice id="parc" abbr="Pa">Parc</choice>
		</prop>
	</props>
	<clues>
		<clue>
			<part>La <ref prop="objet.poignee">poignée</ref> a été trouvée en <ref prop="duree.20">20 minutes</ref>,</part>
			<part>mais pas dans le <ref prop="lieu.sonjardin">jardin de Derek</ref>.</part>
		</clue>
		<clue>
			<part>La <ref prop="sortie.troisieme">troisième</ref> fois qu'il a utilisé son détecteur de métal, Derek a passé plus d'une <ref prop="duree">demi-heure</ref></part>
			<part>à chercher dans le <ref prop="lieu.champ">champ d'un fermier</ref>,</part>
			<part>mais ce n'est pas ce jour-là qu'il a trouvé la <ref prop="objet.capsule">capsule</ref>.</part>
		</clue>
		<clue>
			<part>L'excursion au <ref prop="lieu.parc">parc</ref> n'a donné rien de mieux qu'une vieille <ref prop="objet.cuillere">cuillère</ref>.</part>
		</clue>
		<clue>
			<part>La <ref prop="sortie.quatrieme">quatrième</ref> sortie de Derek a permis de trouver une <ref prop="objet.cle">clé anglaise</ref></part>
			<part>après des recherches ayant duré moins de <ref prop="duree.40">40 minutes</ref>.</part>
			<part>L'excursion de <ref prop="duree.25">25 minutes</ref> à la <ref prop="lieu.plage">plage</ref></part>
			<part>avait eu lieu <ref prop="sortie.quatrieme">avant</ref>.</part>
		</clue>
		<clue>
			<part>La <ref prop="sortie.deuxieme">deuxième</ref> sortie de notre explorateur a duré seulement <ref prop="duree.15">15 minutes</ref>.</part>
		</clue>
	</clues>
	<solution>
		<case recap="La première sortie de Derek a duré 25 minutes et a eu lieu à la plage. Il a trouvé une capsule.">
			<prop prop="sortie" choice="premiere" />
			<prop prop="duree" choice="25" />
			<prop prop="objet" choice="capsule" />
			<prop prop="lieu" choice="plage" />
		</case>
		<case recap="La deuxième sortie de Derek a duré 15 minutes et a eu lieu au parc. Il a trouvé une cuillère.">
			<prop prop="sortie" choice="deuxieme" />
			<prop prop="duree" choice="15" />
			<prop prop="lieu" choice="parc" />
			<prop prop="objet" choice="cuillere" />
		</case>
		<case recap="La troisième sortie de Derek a duré 40 minutes et a eu lieu dans un champ. Il a trouvé un jouet.">
			<prop prop="sortie" choice="troisieme" />
			<prop prop="duree" choice="40" />
			<prop prop="objet" choice="jouet" />
			<prop prop="lieu" choice="champ" />
		</case>
		<case recap="La quatrième sortie de Derek a duré 35 minutes et a eu lieu dans son jardin. Il a trouvé une clé anglaise.">
			<prop prop="sortie" choice="quatrieme" />
			<prop prop="duree" choice="35" />
			<prop prop="objet" choice="cle" />
			<prop prop="lieu" choice="sonjardin" />
		</case>
		<case recap="La cinquième sortie de Derek a duré 20 minutes et a eu lieu dans le jardin d'un ami. Il a trouvé une poignée.">
			<prop prop="sortie" choice="cinquieme" />
			<prop prop="duree" choice="20" />
			<prop prop="objet" choice="poignee" />
			<prop prop="lieu" choice="jardinami" />
		</case>
	</solution>
	<findings>
		<finding clue="1a" formula="poignee=20" />
		<finding clue="1b" formula="poignee!=sonjardin" />
		<finding clue="2a" formula="troisieme&gt;25" />
		<finding clue="2b" formula="troisieme=champ" />
		<finding clue="2c" formula="troisieme!=capsule" />
		<finding clue="3a" formula="parc=cuillere" />
		<finding clue="4a" formula="quatrieme=cle" />
		<finding deducted="true" formula="troisieme|champ=jouet" />
		<finding clue="4b" formula="quatrieme&lt;40" />
		<finding clue="4c" formula="25=#plage" />
		<finding deducted="true" formula="20|poignee=jardinami" />
		<finding clue="4d" formula="#25&lt;#quatrieme" />
		<finding deducted="true" formula="25=capsule=plage" />
		<finding deducted="true" formula="cle|quatrieme=sonjardin" />
		<finding clue="5a" formula="#deuxieme=#15" />
		<finding deducted="true" formula="parc|cuillere=15|deuxieme" />
		<finding deducted="true" formula="cle|jardin|quatrieme=35" />
		<finding deducted="true" formula="jouet|champ|troisieme=40" />
		<finding deducted="true" formula="20|poignee|jardinami=cinquieme" />
		<finding deducted="true" formula="25|capsule|plage=premiere" />
	</findings>
</enigma>
